In [2]:
#creat a sequence of integer from 0 to 30 in step 5.
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [3]:
#Reshapping 3x4 array to 2x2 array
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr= arr.reshape(4,3)
print("/nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)

/nOriginal array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [4]:
#flatten array
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("\nFlattened array;\n",flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Flattened array;
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [8]:
#conversion into types
import numpy as np
arr= np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\n No. of dimensions:\n",arr.ndim)
print("\n Shapeof array:\n",arr.shape)
print("\n Size of array:\n",arr.size)
print("\n Array type:\n",arr.dtype)
newtype=arr.astype('f')
print("\n Converted array element:\n",newtype)
print("\n Converted array type:\n",newtype)      


 No. of dimensions:
 2

 Shapeof array:
 (3, 4)

 Size of array:
 12

 Array type:
 int32

 Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

 Converted array type:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]


In [11]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
