<a href="https://colab.research.google.com/github/Siva714111/Python-Machine-Leaning/blob/main/072_NUMPY_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creating an array
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array Created:\n",a)

Array Created:
 [[1 2 4]
 [5 8 7]]


In [ ]:
#Array with zeros
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Array with same number
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#Creating array with random numbers
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.53844184 0.83375666]
 [0.17534303 0.10150914]]


In [ ]:
#creating a sequence of integer from 0 to 30 instep 5
e=np.arange(0,30,5)
print(e)


[ 0  5 10 15 20 25]


In [ ]:
#Reshapping 3x4 array to 4x3 array
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape(4,3)
print("Original array:\n",arr)
print("Reshaped array:\n",newarr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#flatten a array
flat=arr.flatten()
print("Original array:\n",arr)
print("flatten array:\n",flat)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Conversion into types
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("No, of dimension:\n",arr.ndim)
print("\nShape of the array:\n",arr.shape)
print("\nSize of the array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nConverted array element:\n",newtype)
print("\nConverted array type:\n",newtype.dtype)

No, of dimension:
 2

Shape of the array:
 (3, 4)

Size of the array:
 12

Array type:
 int64

Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted array type:
 float32


In [3]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])
print(p[:,1])
c=p.astype('f')
print(c)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[ 2  5  8 11 14]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
